name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t mini-devops-app .

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.nagaraj2032 }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and push image
      run: |
        docker tag mini-devops-app YOUR_DOCKERHUB_USERNAME/mini-devops-app
        docker push YOUR_DOCKERHUB_USERNAME/mini-devops-app
